extends Incident
class_name Suspect

## Somebody causing trouble: pacing about, mouthing off, refusing to move on.
##
## The police half of what [Casualty] is to the medical service, with the same
## three-beat job -- work the scene, load, deliver -- but nothing here runs down on
## a timer. An unattended disturbance is not *lost*, it just carries on while the
## response bonus drains away: the pressure is the score, not a fuse.
##
## Alive, not a statue. Until the police arrive they pace a few metres around where
## the call opened -- along the pedestrian graph, like everyone else on foot -- and
## when an officer starts the arrest they fight it, swinging until the cuffs go on.
## Once detained they walk back to the spot the call opened on and stand quietly,
## which is also what keeps them within the escorting patrol car's kerbside reach.
##
## Every clip here is a one-shot on the shared rig (the *_Loop variants are not in
## the player -- trusting them left the first suspect in a T-pose), so the loop is
## the same restart pattern [Person] uses: when the clip ends, play it again.

const SUSPECT_GROUP := &"suspects"

@export_group("Arrest")

## Carrying a weapon. An armed suspect cannot simply be walked up to and arrested: an
## ordinary officer is not offered [ApprehendAbility] at all, and armed response has to
## talk them down with [DisarmAbility] first. It is the reason the ARV exists.
@export var armed := false

## How fast one armed-response officer talks them down: about four seconds. Two halve it,
## the same arithmetic as every other [WorkOrder] job.
@export var disarm_per_second := 0.25

## How far through giving up the weapon they are.
var disarmed := 0.0
## Fraction of the arrest completed per second of an officer's work.
@export var detain_per_second := 0.25
## Condition taken off the arresting officer, per second, while they are resisting.
##
## Small: a lone arrest is meant to be *expensive*, not lethal. What it buys is that
## sending two officers, or putting a cordon up first, becomes a decision rather than a
## flourish -- and it gives a disturbance a way to cost you something, which it has never
## had. A suspect still cannot be lost; they can only make you pay.
@export var fight_harm_per_second := 0.06

## How far behind the officer an escorted suspect walks. Far enough not to stand inside
## them, near enough to read as being taken somewhere rather than following by chance.
const ESCORT_GAP := 1.0

## The weapon an armed suspect is holding. Shown while [member armed] and taken away the
## moment they give it up -- which is the readable half of the whole mechanic: the player
## can see at a glance which suspect still has it.
const WEAPON := "res://Assets/Synty/PolygonHeist/Prefab/Weapons/SM_Wep_PistolBandit_01.tscn"
const HAND_BONE := &"RightHand"

var _weapon: Node3D
var _weapon_skeleton: Skeleton3D


## Keeps the pistol on the hand while they are still holding it.
##
## Placed off the bone each frame rather than parented to it, the same reasoning as
## [Person]'s hose nozzle: a `BoneAttachment3D` would have to live inside the character
## scene, and those are regenerated by `build_character.gd`.
func _update_weapon() -> void:
	if not armed:
		if _weapon:
			_weapon.visible = false
		return
	if _weapon == null:
		var packed := load(WEAPON) as PackedScene
		if packed == null:
			return
		_weapon = packed.instantiate() as Node3D
		if _weapon == null:
			return
		_weapon.name = "HeldWeapon"
		Unit.strip_collision(_weapon)
		add_child(_weapon)
	if _weapon_skeleton == null:
		_weapon_skeleton = get_node_or_null(
			"Character/Armature/GeneralSkeleton") as Skeleton3D
	if _weapon_skeleton == null:
		_weapon.visible = false
		return
	var bone := _weapon_skeleton.find_bone(HAND_BONE)
	if bone < 0:
		_weapon.visible = false
		return
	_weapon.visible = true
	_weapon.global_position = _weapon_skeleton.global_transform \
		* _weapon_skeleton.get_bone_global_pose(bone).origin
	_weapon.global_rotation = global_rotation


## Work from a [DisarmOrder]. Once it completes the weapon is gone and the suspect is an
## ordinary arrest -- which is the point: armed response makes the scene safe, it does not
## take the collar.
func disarm(amount: float) -> void:
	if not armed or not active:
		return
	disarmed = minf(disarmed + amount, 1.0)
	if disarmed >= 1.0:
		armed = false


@export_group("Public order")
## Whether this one draws others in. **Off by default**, so the ordinary Disturbance is
## exactly the single mouthy individual it has always been; only the disorder call turns
## it on. A default that recruited would have retuned every crime call in the game while
## claiming to add a feature -- the same trap `Fire.kind`'s default sprang.
@export var recruits := false
## Seconds between one bystander deciding to join in.
@export var recruit_interval := 9.0
## How near a civilian has to be to get involved.
@export var recruit_distance := 7.0
## The most this can grow to, counting everyone already at the scene. Set by the director
## from the roster: a job that outgrew the officers who could ever be sent would be the
## unwinnable version, which this project has already built once and thrown away.
@export var max_group := 4
## How near an officer has to be to take the heat out of it. Comfortably further than
## arrest reach -- an officer standing *among* them is what calms a crowd, and they
## cannot be arresting more than one at a time.
@export var police_reach := 9.0

## Counts down to the next bystander joining. **Starts at a full interval**, set in
## `_ready` because the export is not readable at declaration: at 0.0 the first one
## joined on the very first uncontained frame, which is both wrong (a crowd does not turn
## instantly) and unclearable -- a call that grew the moment it opened could never be
## resolved faster than it recruited, and four shift-end checks went red saying so.
var _recruit_left := 0.0

@export_group("Pacing")
## How far from where the call opened they will wander. Small on purpose: a
## disturbance paces about a spot, it does not leave the scene -- and the escorting
## car's reach is measured from that spot.
@export var wander_radius := 5.5
@export var walk_speed := 1.5
@export var pause_min := 1.0
@export var pause_max := 3.0

@export_group("Visuals")
## Giving an officer-summoning amount of lip. A one-shot, restart-looped.
@export var rowdy_clip := "Idle_Talking"
## Quiet, cuffed, waiting for the car.
@export var calmed_clip := "Idle"
@export var walk_clip := "Walk"
## Alternated while resisting arrest.
@export var fight_clips: Array[String] = ["Punch_Jab", "Punch_Cross"]

@onready var _animation: AnimationPlayer = $Character/AnimationPlayer

## 0 to 1, filled by an officer's work.
var detain_progress := 0.0
## In custody and ready for transport.
var is_detained := false
## Riding in a patrol car: hidden, unpickable, not yet booked in.
var is_loaded := false
## The officer walking them to the car, or null. While set they follow on foot: visible,
## but not pickable, so nothing else can take a target off the officer mid-walk. The same
## arrangement `Casualty.is_carried` uses for a stretcher, and for the same reason.
var escorted_by: Unit
## True while resisting an arrest in progress. Derived from detain() being ticked:
## the work refreshes the heat, the heat decays, and no order has to remember to
## switch it off.
var is_fighting := false
## Who is making the arrest, so the swings land on somebody rather than on the air.
## Passed in by [ApprehendOrder] rather than guessed from the nearest officer: the
## order knows, and a scan would pick the wrong one when two officers are on scene.
var arresting: Unit

## Where the call opened. Captured on the first physics tick, because the director
## positions the node *after* adding it -- _ready still stands at the origin.
var _anchor := Vector3.INF
var _target := Vector3.INF
var _pause := 0.0
var _fight_heat := 0.0
var _fight_swing := 0
var _rng := RandomNumberGenerator.new()


func _ready() -> void:
	super()
	add_to_group(SUSPECT_GROUP)
	# Somebody off the pavement, not the pack's grey mannequin: a disturbance is a
	# member of the public having a bad afternoon.
	_animation = _wear_outfit()
	_recruit_left = recruit_interval
	_rng.seed = hash(name)


func _physics_process(delta: float) -> void:
	# Before the early return: a detained suspect being walked to the car has already
	# been disarmed, and the pistol has to leave with the weapon rather than freeze in
	# mid-air beside them.
	_update_weapon()
	if not active or is_loaded:
		return
	if _anchor == Vector3.INF:
		_anchor = global_position
		_pause = _rng.randf_range(pause_min, pause_max)

	_fight_heat = maxf(_fight_heat - delta, 0.0)
	is_fighting = _fight_heat > 0.0 and not is_detained
	_update_recruiting(delta)

	if is_fighting:
		_target = Vector3.INF
		# They fight whoever has hands on them, and only them -- an officer walking past
		# a scuffle is not in it.
		# **Validity before the cast.** `arresting` is a plain reference to whoever has
		# hands on them, and that officer can be freed -- dissolved back into the station,
		# or torn down with the scene -- while this suspect is still swinging at them.
		# Casting a freed object throws, and a throw here abandons the rest of the frame's
		# behaviour silently.
		var officer := arresting as Person if is_instance_valid(arresting) else null
		if officer:
			officer.hurt(fight_harm_per_second * delta)
		_brawl()
		return
	if escorted_by != null and is_instance_valid(escorted_by):
		_walk_behind(escorted_by, delta)
		return
	if is_detained:
		# Cuffed and nobody walking them: stand where they are. Until August 2026 they
		# trudged back to the spot the call opened on, which was the kerb a patrol car
		# could reach -- that was the *car* coming to them, and the car no longer does.
		_loop(calmed_clip)
		return

	# The disturbance itself: pace a few metres, stop, give it some more mouth.
	if _target != Vector3.INF:
		if _step_towards(_target, delta):
			_target = Vector3.INF
			_pause = _rng.randf_range(pause_min, pause_max)
		return
	_loop(rowdy_clip)
	_pause -= delta
	if _pause <= 0.0:
		_target = _pick_pace()


## Draws a bystander in, unless somebody is containing it.
##
## This is the only thing in the game that gets **worse for want of units** rather than
## for want of time. A fire spreads on its own schedule whatever you do; a disorder call
## spreads only while nobody is standing in it, so arriving is itself the intervention
## and arriving late costs you the size of the job rather than a few seconds of it.
func _update_recruiting(delta: float) -> void:
	if not recruits or is_detained or _group_size() >= max_group:
		return
	# **Contained, and two ways of doing it.** An officer in among them takes the heat
	# out of it, and so does a cordon -- which is the first job `Secure` has ever had.
	# Until now nothing in the game required a ring of cones, and a verb that never
	# matters is a verb the player correctly ignores.
	if _is_contained():
		# Reset rather than pause: containment that merely held the clock would mean a
		# scene could be left half-attended and picked up exactly where it was.
		_recruit_left = recruit_interval
		return
	# Never longer than the interval currently set. `_ready` latches a full interval, so
	# without this a caller that lowers `recruit_interval` afterwards waits out the old
	# one first -- which is a surprise in play and made a check sit through a 9s countdown
	# it thought it had shortened to half a second.
	_recruit_left = minf(_recruit_left, recruit_interval)
	_recruit_left -= delta
	if _recruit_left > 0.0:
		return
	_recruit_left = recruit_interval
	_draw_one_in()


## An officer within reach, or a raised cordon over this spot.
func _is_contained() -> bool:
	for node in get_tree().get_nodes_in_group(Unit.GROUP):
		var unit := node as Unit
		if unit == null or unit.service != Unit.Service.POLICE:
			continue
		# A patrol car parked at the scene is not crowd control; it takes an officer on
		# foot, which is what makes the call about the roster rather than the fleet.
		if unit is Vehicle:
			continue
		var offset := unit.global_position - global_position
		offset.y = 0.0
		if offset.length() <= police_reach:
			return true
	for node in get_tree().get_nodes_in_group(Cordon.GROUP):
		var cordon := node as Cordon
		if cordon and cordon.contains(global_position):
			return true
	return false


## Everyone already in it, so the group stops growing at [member max_group] rather than
## every member growing their own.
func _group_size() -> int:
	var count := 0
	for node in get_tree().get_nodes_in_group(SUSPECT_GROUP):
		var other := node as Suspect
		if other == null or not other.active:
			continue
		var offset := other.global_position - global_position
		offset.y = 0.0
		if offset.length() <= recruit_distance * 2.5:
			count += 1
	return count


## Turns the nearest bystander into one more of them, wearing what they were wearing --
## the same thing a blast does to the person standing in it, and for the same reason: the
## crowd in this game is made of people, not spawn points.
func _draw_one_in() -> void:
	var parent := get_parent()
	if parent == null:
		return
	var nearest: Civilian = null
	var best := recruit_distance
	for node in get_tree().get_nodes_in_group(Unit.GROUP):
		var civilian := node as Civilian
		if civilian == null:
			continue
		# A disturbance does not recruit the missing child -- partly tone, mostly that
		# converting them frees the body their report is scanning for.
		if civilian is ChildWanderer:
			continue
		var offset := civilian.global_position - global_position
		offset.y = 0.0
		if offset.length() < best:
			best = offset.length()
			nearest = civilian
	if nearest == null:
		return
	var joined := (load("res://Game/Incidents/Suspect.tscn") as PackedScene) \
		.instantiate() as Suspect
	if joined == null:
		return
	joined.outfit = nearest.outfit_scene()
	joined.flavour = "Public disorder"
	joined.recruits = true
	joined.max_group = max_group
	parent.add_child(joined)
	joined.global_position = nearest.global_position
	nearest.queue_free()


## Taken in hand by an officer, to be walked to the car.
func walk_with(officer: Unit) -> void:
	if not active or not is_detained or is_loaded:
		return
	escorted_by = officer
	# Not pickable while being walked, so a second order cannot take them off the
	# officer halfway there and leave two units arguing over one suspect.
	$Collision.set_deferred("disabled", true)


## Let go, wherever they happen to be standing. Cancelling an escort has to leave a
## suspect that is still detained and still collectable, not one stuck to a freed order.
func let_go() -> void:
	escorted_by = null
	if active and not is_loaded:
		$Collision.set_deferred("disabled", false)


## Follows a step behind whoever is walking them.
func _walk_behind(officer: Unit, delta: float) -> void:
	var behind := officer.global_position
	var back := officer.global_basis.z
	back.y = 0.0
	if back.length() > 0.01:
		behind += back.normalized() * ESCORT_GAP
	if _step_towards(behind, delta):
		_face(officer.global_position)
		_loop(calmed_clip)


## An officer's work. At 1 the suspect is in custody and ready for the car.
## Being worked on is what they fight: each tick refreshes the scuffle, and
## [param by] is who they square up to.
func detain(amount: float, by: Unit = null) -> void:
	if not active or is_detained:
		return
	_fight_heat = 0.5
	if by != null:
		arresting = by
	detain_progress = minf(detain_progress + amount, 1.0)
	if detain_progress >= 1.0:
		is_detained = true
		is_fighting = false
		_fight_heat = 0.0
		arresting = null


func describe_state() -> String:
	# Both of these name the *destination*. "Aboard, en route" was true and useless:
	# the first thing anyone asked after their first arrest was what happens now, and
	# the answer -- drive them to the station -- was nowhere on screen.
	if is_loaded:
		return "aboard, for the station"
	if is_detained:
		return "in custody, needs a patrol car"
	if is_fighting:
		return "resisting arrest"
	if detain_progress > 0.0:
		return "being detained"
	return "causing a disturbance"


## Same stages as the casualty's: worked, then loaded, then booked in.
func progress() -> float:
	if is_loaded:
		return 0.9
	if is_detained:
		return 0.5
	return detain_progress * 0.5


## Climbs into the back of a patrol car. The seat is claimed by
## [method Vehicle.load_suspect] first; this is only the passenger's half of it.
func load_into(_vehicle: Vehicle) -> void:
	if is_loaded or not is_detained:
		return
	is_loaded = true
	visible = false
	$Collision.set_deferred("disabled", true)


## Booked in at the station: the job closes, successfully.
func deliver() -> void:
	_finish(true)


# --- Moving and animating -----------------------------------------------------

## Glides toward [param point], facing travel, walking clip on. True on arrival.
## The body is a StaticBody3D moved by hand, exactly as the stretcher moves a
## casualty -- it collides with nothing, so there is nothing to get wrong.
func _step_towards(point: Vector3, delta: float) -> bool:
	var offset := point - global_position
	offset.y = 0.0
	if offset.length() <= 0.25:
		return true
	var step := offset.normalized() * walk_speed * delta
	global_position += step
	_face(point)
	_loop(walk_clip)
	return false


## Turn to look at a world point. Aims the node's -Z, which the Character child's
## 180 yaw turns into the model looking that way -- the same convention (and the
## same trap) as [method Person.face_towards].
func _face(point: Vector3) -> void:
	var flat := point - global_position
	flat.y = 0.0
	if flat.length() < 0.05:
		return
	rotation.y = atan2(flat.x, flat.z) + PI


## Somewhere legal to pace to: an adjacent tile on the pedestrian graph, kept
## inside the wander radius. A suspect on a tile the graph does not serve -- the
## middle of a road, say, where the tests like to put them -- simply stands still
## and keeps talking.
func _pick_pace() -> Vector3:
	var col := int(floorf((_anchor.x - CityGrid.ORIGIN) / CityGrid.TILE))
	var row := int(floorf((_anchor.z - CityGrid.ORIGIN) / CityGrid.TILE))
	var spots: Array[Vector3] = [_anchor]
	for move in CityGrid.walk_moves(col, row):
		var spot := CityGrid.tile_centre(move.x, move.y)
		if Vector2(spot.x - _anchor.x, spot.z - _anchor.z).length() <= wander_radius:
			spots.append(spot)
	var pick := spots[_rng.randi_range(0, spots.size() - 1)]
	# Scattered a little so the pacing does not retrace one line.
	return pick + Vector3(_rng.randf_range(-0.8, 0.8), 0.0, _rng.randf_range(-0.8, 0.8))


## The scuffle: squared up to the officer, the two punch one-shots alternated as
## each lands. Facing is re-aimed every frame -- the officer shuffles about while
## working, and a suspect swinging past their shoulder reads as punching the air.
func _brawl() -> void:
	if is_instance_valid(arresting):
		_face(arresting.global_position)
	if _animation == null:
		return
	if _animation.current_animation == "":
		_fight_swing = (_fight_swing + 1) % fight_clips.size()
	var swing := fight_clips[_fight_swing]
	if _animation.current_animation != swing and _animation.has_animation(swing):
		_animation.play(swing, 0.1)


## The restart loop for one-shot clips: play it, and play it again when it ends.
func _loop(clip: String) -> void:
	if _animation == null or not _animation.has_animation(clip):
		return
	if _animation.current_animation == "":
		_animation.play(clip, 0.2)
	elif _animation.current_animation != clip \
			and _animation.current_animation not in fight_clips:
		_animation.play(clip, 0.2)