extends RefCounted
class_name AudioBuses

## The three audio buses, created at runtime rather than shipped as a bus layout.
##
## Until August 2026 there was exactly one bus -- Master -- and the settings card's single
## slider drove it. That was fine while everything was a sound effect. It stops being fine
## the moment music arrives: a bed that plays under the whole shift has to be balanced
## against the sirens and the city, and with one bus the only way to turn the music down
## is to turn the game down.
##
## **Made here, not in `default_bus_layout.tres`.** A bus layout is a resource the editor
## owns, and this project has a standing rule that generated things are generated by a
## script you can read. Three buses in code is smaller than a `.tres` nobody can diff, and
## it means a scene that forgets to set one up still works -- `ensure()` is idempotent and
## anything can call it.
##
## Master stays the one the settings slider drives, so the existing volume setting keeps
## its meaning: it is the whole game's level, and the two below it are balance.

const MUSIC := &"Music"
const UI := &"UI"
## Everything the *world* makes: sirens, engines, the fire's crackle, the city bed and
## the dispatch radio. Added a session after Music, and the reason is the asymmetry it
## fixed -- with Music on its own bus and effects on Master, the only way to quieten the
## sirens was to quieten the music with them, which is precisely the balance the music
## slider had just been added to let you set.
const SFX := &"Sfx"

## Where the music sits relative to everything else, before the player touches anything.
## A bed is meant to be noticed on the way in and forgotten by the first shout.
##
## **-26, down from -18** (August 2026): the first cut was audibly too loud over the city.
## Part of that was arithmetic rather than taste -- the settings slider steps in 0.05 and
## -18 dB is 0.126 linear, which the slider rounds *up* to 0.15, so the bed played about
## 1.5 dB above the number written here. -26 dB is 0.0501, which snaps to 0.05 and lands
## where it was aimed.
const MUSIC_DEFAULT_DB := -26.0


## Creates the buses if they are not already there. Safe to call from anything, at any
## time, as many times as you like -- which is the point, since the HUD, the main menu and
## the suite all need them and none of them owns the others.
static func ensure() -> void:
	for name: StringName in [MUSIC, UI, SFX]:
		if AudioServer.get_bus_index(name) >= 0:
			continue
		var index := AudioServer.get_bus_count()
		AudioServer.add_bus(index)
		AudioServer.set_bus_name(index, name)
		# Routed through Master, so the existing master-volume setting still turns
		# everything down together.
		AudioServer.set_bus_send(index, &"Master")


## A bus's level as a linear 0..1, for a settings slider to read and write.
static func volume(bus: StringName) -> float:
	var index := AudioServer.get_bus_index(bus)
	if index < 0:
		return 1.0
	return db_to_linear(AudioServer.get_bus_volume_db(index))


static func set_volume(bus: StringName, linear: float) -> void:
	ensure()
	var index := AudioServer.get_bus_index(bus)
	if index < 0:
		return
	# Clamped off zero before the log: `linear_to_db(0)` is -inf, which serialises into
	# the settings file as `inf` and comes back as a bus that can never be turned up.
	AudioServer.set_bus_volume_db(index, linear_to_db(maxf(linear, 0.0001)))


## Kept as named wrappers because `set_music_volume` reads better at the call site than
## `set_volume(AudioBuses.MUSIC, ...)`, and because the music one already had callers.
static func music_volume() -> float:
	return volume(MUSIC)


static func set_music_volume(linear: float) -> void:
	set_volume(MUSIC, linear)


static func sfx_volume() -> float:
	return volume(SFX)


static func set_sfx_volume(linear: float) -> void:
	set_volume(SFX, linear)
