extends Node
class_name ScenarioDirector

## Plays one designed shift: a timeline of calls, a par time, and a win when the last
## of them is cleared.
##
## Built at runtime by [GameMenu] rather than shipped in the scene, which is the whole
## reason this is cheap. `Playground.tscn` is generated by `build_map.gd` and adding a
## node to it means editing the generator and regenerating with a window; a node the
## menu creates and adds to the running scene needs neither.
##
## It borrows everything. The freeplay [Director] already knows how to place all
## sixteen call kinds sensibly on the district, so a wave is `open_kind()` in a loop
## and no scenario has to know where a junction is. [Mission] already runs the scripted
## win rule -- map goes clear, shout is won -- and already scores a shout in freeplay's
## own currency. What this adds is the *order*, the *clock*, and the one flag that
## makes staging possible.
##
## **The freeplay director stays inert.** `begin_shift()` is never called, so
## `Mission.scoring` stays false and the scripted win path is live. A scenario is a
## shout, not a shift.

## How often the timeline is consulted. Waves are tens of seconds apart; a quarter of
## a second is far finer than anything here needs and costs nothing.
const TICK := 0.25

## The scenario being played, as one of [constant Scenarios.ALL].
var scenario: Dictionary = {}
var elapsed := 0.0
## Index of the next wave to open.
var _next := 0
var _running := false
var _clock := 0.0


func begin(chosen: Dictionary) -> void:
	scenario = chosen
	elapsed = 0.0
	_next = 0
	_clock = 0.0
	var mission := _mission()
	if mission:
		# Its own clean sheet, and the par it is judged against. Nothing is paid and
		# no record is set -- see Mission.shout_score.
		mission.reset_tallies()
		mission.par_seconds = float(scenario.get("par", 0.0))
		# Held from the first frame, because the map is clear until the first wave
		# lands and a clear map is what the scripted rule reads as a job done.
		mission.more_to_come = true
		# Back to RUNNING through the state change, so the HUD hears it: a scenario
		# picked after another one was won would otherwise start against a WON mission
		# -- which `_evaluate` refuses to move off -- under the last one's debrief
		# modal, still holding the mouse.
		mission._set_state(Mission.State.RUNNING)
	_running = true


func _process(delta: float) -> void:
	if not _running:
		return
	elapsed += delta
	_clock += delta
	if _clock < TICK:
		return
	_clock = 0.0

	var waves: Array = scenario.get("waves", [])
	while _next < waves.size() and elapsed >= float(waves[_next].get("at", 0.0)):
		var director := _director()
		for kind: StringName in waves[_next].get("kinds", []):
			if director:
				director.open_kind(kind)
		_next += 1

	var mission := _mission()
	if mission:
		# The flag goes down only when the last wave is out. Until then the map going
		# clear between waves means the player is ahead, not finished.
		mission.more_to_come = _next < waves.size()
		if mission.state != Mission.State.RUNNING:
			_running = false


## Seconds left against par, negative once it is over. The status strip reads this.
func par_remaining() -> float:
	return float(scenario.get("par", 0.0)) - elapsed


func scenario_name() -> String:
	return str(scenario.get("name", ""))


## Found among this node's own siblings, by type.
##
## Neither [Mission] nor [Director] is in a group -- the HUD reaches them by exported
## path, which a node created at runtime has no way to be given. By type rather than
## by name because a name is a thing a generator can rename, and `is Mission` cannot
## be got wrong.
func _mission() -> Mission:
	for sibling in get_parent().get_children() if get_parent() else []:
		if sibling is Mission:
			return sibling as Mission
	return null


func _director() -> Director:
	for sibling in get_parent().get_children() if get_parent() else []:
		if sibling is Director:
			return sibling as Director
	return null
