extends RefCounted
class_name HeldItem

## Where a prop sits in somebody's hand, and the one place that decides it.
##
## **Two things were missing before this existed, and only one of them looked like a bug.**
## Both places that put a prop in a hand -- [Person] for the officer's sidearm, [Suspect]
## for the robber's -- did exactly this:
##
## [codeblock]
## item.global_position = skeleton.global_transform * pose(bone).origin
## item.global_rotation = global_rotation
## [/codeblock]
##
## So a prop was dropped on the hand bone's *origin* with no correction of any kind, which
## takes every pack model exactly as its author left it: a pistol whose origin sits at the
## muzzle hangs a barrel-length out of the fist, and one whose grip runs along +X points
## sideways. There was nowhere to put a fix even once you knew the number. That is
## [constant OFFSETS].
##
## The second is subtler and is why a still image cannot settle this. `global_rotation` is
## the **body's** yaw, so the prop tracked the torso and not the wrist -- it would look
## right in one pose and wrong the moment a clip rotated the hand, and the pistol pose and
## the walk cycle disagreed with each other. Placement reads the bone's full basis now, so
## a prop turns with the hand holding it.
##
## Not parented to a `BoneAttachment3D`, and that stays deliberate: the attachment would
## have to live *inside* the character scene, and all eleven of those are generated by
## `build_character.gd`, which would throw it away on the next rebuild.

## The bone everything is held in. Both callers named this separately and identically;
## naming it once is the point of this class.
const HAND_BONE := &"RightHand"

## Correction per prop, in the **hand bone's own space**: metres, then degrees, then a
## uniform scale factor.
##
## **Authored by eye, in a window, and there is no other way.** A prop is right when it
## looks right across the clips the unit actually plays -- not in one pose -- so these
## numbers come out of `Game/HandCalibration.tscn`, which is built for exactly that and
## prints a finished row to paste in here. Nothing headless can judge them: the checks
## that guard this file assert that a prop *resolves*, that it stays near the hand, and
## that it turns with the wrist. Whether it looks like it is being held is a human's call.
##
## Degrees rather than radians because a person has to read and type these.
const OFFSETS := {
	"res://Assets/Synty/PolygonHeist/Prefab/Weapons/SM_Wep_PistolSwat_01.tscn": {
		"pos": Vector3.ZERO, "rot": Vector3.ZERO, "scale": 1.0,
	},
	"res://Assets/Synty/PolygonHeist/Prefab/Weapons/SM_Wep_PistolBandit_01.tscn": {
		"pos": Vector3.ZERO, "rot": Vector3.ZERO, "scale": 1.0,
	},
}

## What a prop with no row of its own gets: the old behaviour, minus the body-yaw mistake.
## A prop reaching this is not an error -- it is one nobody has calibrated yet, and it
## should sit on the hand rather than vanish.
const NEUTRAL := {"pos": Vector3.ZERO, "rot": Vector3.ZERO, "scale": 1.0}


## The correction for [param source], or [constant NEUTRAL] if it has none.
static func offset_for(source: String) -> Dictionary:
	return OFFSETS.get(source, NEUTRAL)


## Puts [param item] in [param skeleton]'s hand, corrected. False when there is no hand to
## put it in -- a character without a skeleton, or a rig missing the bone -- which every
## caller treats as "hide it" rather than as a fault.
##
## [param override] stands in for the table row, and exists for two callers rather than
## as a convenience. `Game/HandCalibration.tscn` passes the numbers the user is nudging,
## so the harness shows the *same* composition the game ships rather than its own copy of
## it -- this class was written to end exactly that kind of duplication and would have
## reintroduced it. And the suite passes a known correction to prove the correction is
## applied at all: every shipped row is zero today, so a `place()` that ignored the table
## outright would put every prop in precisely the right place and nothing would notice.
static func place(item: Node3D, skeleton: Skeleton3D, source: String,
		override: Dictionary = {}) -> bool:
	if item == null or skeleton == null:
		return false
	var bone := skeleton.find_bone(HAND_BONE)
	if bone < 0:
		return false
	# **The full pose, not just its origin.** `get_bone_global_pose` returns a transform;
	# taking `.origin` off it was what threw the wrist away.
	var hand := skeleton.global_transform * skeleton.get_bone_global_pose(bone)
	item.global_transform = hand * to_transform(
		override if not override.is_empty() else offset_for(source))
	return true


## The correction for [param source] as a transform.
static func local_fix(source: String) -> Transform3D:
	return to_transform(offset_for(source))


## A correction row as a transform. Degrees in, radians out; the one place the table's
## units are interpreted, so the harness and the game cannot read them differently.
static func to_transform(fix: Dictionary) -> Transform3D:
	var degrees: Vector3 = fix.get("rot", Vector3.ZERO)
	var basis := Basis.from_euler(Vector3(
		deg_to_rad(degrees.x), deg_to_rad(degrees.y), deg_to_rad(degrees.z)))
	var factor := float(fix.get("scale", 1.0))
	return Transform3D(basis.scaled(Vector3.ONE * factor),
		fix.get("pos", Vector3.ZERO))


## The skeleton a held prop hangs off, looked up the one way both callers looked it up.
static func skeleton_of(body: Node) -> Skeleton3D:
	return body.get_node_or_null("Character/Armature/GeneralSkeleton") as Skeleton3D
